---
name: Test Container

on:
  pull_request:
  workflow_dispatch:

jobs:
  # Test the image builds and works correctly.
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Test building image.
        run: docker_hash=$(docker build . -q)

      - name: Run the built image.
        run: docker run --privileged --volume $(pwd):/github/workspace/buluma/ansible-role-example:z --volume /var/run/docker.sock:/var/run/docker.sock:z --tty --interactive --env GITHUB_REPOSITORY="buluma/ansible-role-libvirt" --env ANSIBLE_ROLES_PATH="../" ${docker_hash}
